apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress-jondepannage
    annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
    rules:
        - host: jondepannage.tsukoyachi.ovh
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: jondepannage
                            port:
                                number: 80
    tls:
        - hosts:
              - jondepannage.tsukoyachi.ovh
          secretName: jondepannage.tsukoyachi-tls
