apiVersion: v1
kind: Service
metadata:
    labels:
        io.kompose.service: jondepannage
    name: jondepannage
    namespace: jondepannage
spec:
    ports:
        - name: 'http'
          port: 80
          targetPort: 3000
    selector:
        io.kompose.service: jondepannage
