name: CI

on:
    push:
        branches:
            - master

permissions: write-all

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - name: Setup Git
              run: |
                  git config user.name "GitHub Bot"
                  git config user.email "gituser@example.com"

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: |
                      ghcr.io/tsukoyachi/jondepannage:${{ github.sha }}
                      ghcr.io/tsukoyachi/jondepannage:latest
